// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url 'https://dl.google.com/dl/android/maven2/' }
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
    }
}
plugins {
    id "org.sonarqube" version "7.3.0.8198"
}
allprojects {
    repositories {
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url 'https://dl.google.com/dl/android/maven2/' }
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

sonar {
    properties {
        property "sonar.projectKey", "GuinaF2_WifiIndoorPositioningSystem"
        property "sonar.organization", "guinaf2"
    }
}
