name: CI Pipeline Legado - Testes e Cobertura

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Baixando o repositório
      uses: actions/checkout@v4

    - name: Configurando o Java 8 (Crucial para o Gradle 2016)
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Exorcizando arquivos fantasmas do Windows
      run: find . -name "local.properties" -type f -delete

    - name: Dando permissão de execução ao Gradle
      run: chmod +x gradlew

    - name: Limpeza, Testes Unitários e Relatório JaCoCo
      run: ./gradlew clean testDebugUnitTest jacocoTestReport
