name: CI Pipeline Legado - Testes e Cobertura

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Baixando o repositório
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Necessário para o Sonar analisar o histórico do repositório

    - name: Configurando o Java 8 (Crucial para o Gradle 2016)
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Exorcizando arquivos fantasmas do Windows
      run: find . -name "local.properties" -type f -delete

    - name: Dando permissão de execução ao Gradle
      run: chmod +x gradlew

    - name: Limpeza, Testes Unitários e Relatório JaCoCo
      run: ./gradlew clean testDebugUnitTest jacocoTestReport

    - name: Análise Estática no SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=GuinaF2_WifiIndoorPositioningSystem
          -Dsonar.organization=guinaf2
          -Dsonar.java.binaries=app/build/intermediates/classes/debug
          -Dsonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
